# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ include "mysql.fullname" . }}-init-file
data: 
  init.sql: |- 
    CREATE DATABASE IF NOT EXISTS ekba_kb;
    USE ekba_kb;
