# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datafiles
  namespace: ekba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-dynamic
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opea-models
  namespace: ekba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-dynamic
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovms-embedding
  namespace: ekba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-dynamic
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovms-rerank
  namespace: ekba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-dynamic
  resources:
    requests:
      storage: 50Gi

