# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM registry.cn-hangzhou.aliyuncs.com/docker_workspace_hub/python:3.10.12-slim

ENV LANG=C.UTF-8

ARG ARCH="cpu"

RUN rm -rf /var/lib/apt/lists/* && \
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends --fix-missing \
        build-essential \
        default-jre \
        libgl1-mesa-glx \
        libjemalloc-dev \
        libreoffice \
        tesseract-ocr \
        ghostscript \
        python3-tk \
        wget

RUN useradd -ms /bin/bash user
# embed paddleocr and embedding models
ADD comps/dataprep/magic-pdf.json /home/user
RUN chown -R user:user /home/user/

USER user

RUN mkdir -p ~/.pip && \
    echo "[global]" > ~/.pip/pip.conf && \
    echo "index-url = https://pypi.tuna.tsinghua.edu.cn/simple" >> ~/.pip/pip.conf && \
    echo "trusted-host = pypi.tuna.tsinghua.edu.cn" >> ~/.pip/pip.conf

RUN pip install --no-cache-dir -U magic-pdf[full]==1.3.12 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --no-cache-dir transformers==4.49.0 -i https://pypi.tuna.tsinghua.edu.cn/simple


COPY comps/dataprep/requirements.txt  /home/user/
RUN pip install --no-cache-dir --upgrade pip setuptools wheel -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --no-cache-dir -r /home/user/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

ENV PYTHONPATH=/home/user
COPY --chown=user:user comps /home/user/comps
RUN mkdir -p /home/user/comps/dataprep/uploaded_files
RUN mkdir -p /home/user/models

WORKDIR /home/user/comps/dataprep

ENTRYPOINT ["python", "main.py"]